name: nd_care-net
dependencies:
    - python=3.6.9
    - numpy
    - pandas
    - matplotlib
    - tabulate
    - jupyter
    - jupyterlab
    - xlrd=1.2.0
    - pip
    - pytorch
    - torchvision
    - cudatoolkit=10.1
    - pip:
        - sklearn
        - networkx
        - xmlschema
        - gensim
        - nltk
        - transformers
        - sentence-transformers
        - texttable
        - jupyter-repo2docker
