channels:
    - conda-forge
dependencies:
    - python=3.6.9
    - numpy
    - pandas
    - seaborn
    - tabulate
    - xlrd
    - pip
    - pillow
    - tqdm
    - ipywidgets
    - networkx
    - gensim
    - nltk
    - scipy
    - pip:
        - h2o4gpu
        - xmlschema
        - transformers
        - sentence-transformers
        - texttable
        - jupyter-repo2docker
        - gdown
        - comet-ml
        - jupyterlab-git
        - wordcloud
        - pyldavis
        - tensorflow-text
