name: nd_care-net
dependencies:
    - python=3.6.9
    - numpy
    - pandas
    - matplotlib
    - tabulate
    - jupyter
    - jupyterlab
    - xlrd=1.2.0
    - pip
    - pillow
    - pytorch
    - torchvision
    - cudatoolkit=10.1
    - nb_conda_kernels
    - deepdish
    - tqdm
    - ipywidgets
    - sklearn
    - networkx
    - gensim
    - nltk
    - scipy
    - pip:
        - xmlschema
        - transformers
        - sentence-transformers
        - texttable
        - jupyter-repo2docker
        - gdown
        - comet-ml
        - jupyterlab-git
        - wordcloud
