name: nd_care-net
dependencies:
    - python=3.6.9
    - numpy=1.17.2
    - pandas=0.25.2
    - seaborn=0.10.0
    - tabulate=0.8.3
    - jupyter=1.0.0
    - jupyterlab=1.2.3
    - xlrd=1.2.0
    - pip=19.3.1
    - pillow=7.0.0
    - pytorch=1.3.1
    - torchvision=0.4.2
    - cudatoolkit=10.2.89
    - nb_conda_kernels=2.2.2
    - deepdish=0.3.4
    - tqdm=4.37.0
    - ipywidgets=7.5.1
    - h2o4gpu=0.2.0
    - networkx=2.4
    - gensim=3.8.1
    - nltk=3.4.5
    - scipy=1.3.1
    - cudnn=7.6.5
    - pip:
        - xmlschema
        - transformers
        - sentence-transformers
        - texttable
        - jupyter-repo2docker
        - gdown
        - comet-ml
        - jupyterlab-git
        - wordcloud
