#! /bin/bash

gdown "https://drive.google.com/uc?id=1MndgLu6togwrlFGsPQ4TfVYMPaq97Kte" -O data.tar.gz
aunpack data.tar.gz
rm data.tar.gz
# jupyter lab extension for committing to github
jupyter lab build
# install cuda version 10.2
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb
dpkg -i cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb
apt-key add /var/cuda-repo-10-2-local-10.2.89-440.33.01/7fa2af80.pub
apt-get updatesudo apt-get -y install cuda
#mkdir ~/.jupyter
#cp binder/.jupyter ~/
#cp binder/.jupyter/* /srv/conda/envs/notebook/etc/jupyter/
